// mock/properties.ts

// import { Property } from "@/types/property";

// export const properties: Property[] = [
//   {
//     id: 1,
//     title: "Elegant Contemporary Villa with a Garden",
//     description: "Lorem ipsum dolor sit amet consectetur.",
//     image: "/assets/images/villa (1).jpg",
//     tags: ["VILLA", "1 BEDROOM", "2 BATHROOM", "839 SQ.FT"],
//   },
//   {
//     id: 2,
//     title: "Prime Location Generous Space High Return",
//     description: "Lorem ipsum dolor sit amet consectetur.",
//     image: "/assets/images/villa (2).jpg",
//     tags: ["VILLA", "1 BEDROOM", "2 BATHROOM", "839 SQ.FT"],
//   },
//   {
//     id: 3,
//     title: "Luxury Modern Villa",
//     description:
//       "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
//     image: "/assets/images/villa (3).jpg",
//     tags: ["VILLA", "1 BEDROOM", "2 BATHROOM", "839 SQ.FT"],
//   },
//   {
//     id: 4,
//     title: "Luxury Modern Villa",
//     description:
//       "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
//     image: "/assets/images/villa (3).jpg",
//     tags: ["VILLA", "1 BEDROOM", "2 BATHROOM", "839 SQ.FT"],
//   },
// ];

import { Property } from "@/types/property";

export const properties: Property[] = [
  {
    id: "1",
    title: "Modern Villa",
    price: 2700000,
    type: "villa",
    beds: 4,
    areasize: 3200,
    location: "JVT Dubai",
    purpose: "buy",
    amenities: ["pool", "garden"],
    slug: "modern-villa-jvt",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (3).jpg",
    tags: ["VILLA", "1 BEDROOM", "2 BATHROOM", "839 SQ.FT"],
  },
  {
    id: "4",
    title: "City Apartment",
    price: 850000,
    type: "apartment",
    beds: 2,
    areasize: 1100,
    location: "Business Bay",
    purpose: "buy",
    amenities: ["gym"],
    slug: "city-apartment-business-bay",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (3).jpg",
    tags: ["APARTMENT", "2 BEDROOM", "2 BATHROOM", "1100 SQ.FT"],
  },
  {
    id: "5",
    title: "Garden View Villa",
    price: 3150000,
    type: "villa",
    beds: 5,
    areasize: 4100,
    location: "Arabian Ranches",
    purpose: "buy",
    amenities: ["garden", "pool"],
    slug: "garden-view-villa-arabian-ranches",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (2).jpg",
    tags: ["VILLA", "5 BEDROOM", "4 BATHROOM", "4100 SQ.FT"],
  },
  {
    id: "6",
    title: "Marina Skyline Apartment",
    price: 1250000,
    type: "apartment",
    beds: 3,
    areasize: 1650,
    location: "Dubai Marina",
    purpose: "buy",
    amenities: ["gym", "pool"],
    slug: "marina-skyline-apartment",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (1).jpg",
    tags: ["APARTMENT", "3 BEDROOM", "3 BATHROOM", "1650 SQ.FT"],
  },
  {
    id: "7",
    title: "Downtown Studio Apartment",
    price: 650000,
    type: "apartment",
    beds: 1,
    areasize: 520,
    location: "Downtown Dubai",
    purpose: "buy",
    amenities: ["gym"],
    slug: "downtown-studio-apartment",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (3).jpg",
    tags: ["APARTMENT", "1 BEDROOM", "1 BATHROOM", "520 SQ.FT"],
  },
  {
    id: "8",
    title: "Palm Beachfront Penthouse",
    price: 8900000,
    type: "penthouse",
    beds: 4,
    areasize: 6200,
    location: "Palm Jumeirah",
    purpose: "buy",
    amenities: ["pool", "gym", "garden"],
    slug: "palm-beachfront-penthouse",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (2).jpg",
    tags: ["PENTHOUSE", "4 BEDROOM", "5 BATHROOM", "6200 SQ.FT"],
  },
  {
    id: "15",
    title: "Canal View Apartment",
    price: 980000,
    type: "apartment",
    beds: 2,
    areasize: 1250,
    location: "Business Bay",
    purpose: "buy",
    amenities: ["gym", "pool"],
    slug: "canal-view-apartment-business-bay",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (1).jpg",
    tags: ["APARTMENT", "2 BEDROOM", "2 BATHROOM", "1250 SQ.FT"],
  },
  {
    id: "16",
    title: "JVC Family Apartment",
    price: 790000,
    type: "apartment",
    beds: 2,
    areasize: 980,
    location: "JVC",
    purpose: "buy",
    amenities: ["gym"],
    slug: "jvc-family-apartment",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (3).jpg",
    tags: ["APARTMENT", "2 BEDROOM", "2 BATHROOM", "980 SQ.FT"],
  },
  {
    id: "17",
    title: "Creek Harbour Apartment",
    price: 1350000,
    type: "apartment",
    beds: 3,
    areasize: 1700,
    location: "Dubai Creek Harbour",
    purpose: "buy",
    amenities: ["gym", "pool"],
    slug: "creek-harbour-apartment",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (2).jpg",
    tags: ["APARTMENT", "3 BEDROOM", "3 BATHROOM", "1700 SQ.FT"],
  },
  {
    id: "18",
    title: "Hills Estate Villa",
    price: 5600000,
    type: "villa",
    beds: 5,
    areasize: 5200,
    location: "Dubai Hills Estate",
    purpose: "buy",
    amenities: ["garden", "pool"],
    slug: "hills-estate-villa",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (1).jpg",
    tags: ["VILLA", "5 BEDROOM", "5 BATHROOM", "5200 SQ.FT"],
  },
  {
    id: "19",
    title: "Townhouse Style Villa",
    price: 2100000,
    type: "villa",
    beds: 3,
    areasize: 2400,
    location: "Dubai South",
    purpose: "buy",
    amenities: ["garden"],
    slug: "townhouse-style-villa-dubai-south",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (2).jpg",
    tags: ["VILLA", "3 BEDROOM", "3 BATHROOM", "2400 SQ.FT"],
  },
  {
    id: "20",
    title: "Prime Location Apartment",
    price: 1150000,
    type: "apartment",
    beds: 2,
    areasize: 1320,
    location: "Downtown Dubai",
    purpose: "buy",
    amenities: ["gym", "pool"],
    slug: "prime-location-apartment-downtown",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (3).jpg",
    tags: ["APARTMENT", "2 BEDROOM", "2 BATHROOM", "1320 SQ.FT"],
  },
  {
    id: "21",
    title: "Lagoon View Villa",
    price: 4750000,
    type: "villa",
    beds: 4,
    areasize: 4600,
    location: "Damac Lagoons",
    purpose: "buy",
    amenities: ["pool", "garden"],
    slug: "lagoon-view-villa-damac-lagoons",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (1).jpg",
    tags: ["VILLA", "4 BEDROOM", "4 BATHROOM", "4600 SQ.FT"],
  },
  {
    id: "22",
    title: "Minimal Studio Apartment",
    price: 520000,
    type: "apartment",
    beds: 1,
    areasize: 460,
    location: "Al Furjan",
    purpose: "buy",
    amenities: [],
    slug: "minimal-studio-apartment-al-furjan",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (2).jpg",
    tags: ["APARTMENT", "1 BEDROOM", "1 BATHROOM", "460 SQ.FT"],
  },
  {
    id: "23",
    title: "Sea View Penthouse",
    price: 6400000,
    type: "penthouse",
    beds: 3,
    areasize: 4100,
    location: "JBR",
    purpose: "buy",
    amenities: ["gym", "pool"],
    slug: "sea-view-penthouse-jbr",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (3).jpg",
    tags: ["PENTHOUSE", "3 BEDROOM", "4 BATHROOM", "4100 SQ.FT"],
  },
  {
    id: "24",
    title: "Park Facing Apartment",
    price: 870000,
    type: "apartment",
    beds: 2,
    areasize: 1050,
    location: "Town Square",
    purpose: "buy",
    amenities: ["gym"],
    slug: "park-facing-apartment-town-square",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (1).jpg",
    tags: ["APARTMENT", "2 BEDROOM", "2 BATHROOM", "1050 SQ.FT"],
  },
  {
    id: "25",
    title: "Golf Course Villa",
    price: 6900000,
    type: "villa",
    beds: 6,
    areasize: 6800,
    location: "Emirates Hills",
    purpose: "buy",
    amenities: ["garden", "pool"],
    slug: "golf-course-villa-emirates-hills",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (2).jpg",
    tags: ["VILLA", "6 BEDROOM", "6 BATHROOM", "6800 SQ.FT"],
  },
  {
    id: "26",
    title: "Smart Home Apartment",
    price: 990000,
    type: "apartment",
    beds: 2,
    areasize: 1180,
    location: "Dubai Hills Estate",
    purpose: "buy",
    amenities: ["gym", "pool"],
    slug: "smart-home-apartment-dubai-hills",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (3).jpg",
    tags: ["APARTMENT", "2 BEDROOM", "2 BATHROOM", "1180 SQ.FT"],
  },
  {
    id: "27",
    title: "Beachside Apartment",
    price: 1550000,
    type: "apartment",
    beds: 2,
    areasize: 1400,
    location: "Emaar Beachfront",
    purpose: "buy",
    amenities: ["gym", "pool"],
    slug: "beachside-apartment-emaar-beachfront",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (1).jpg",
    tags: ["APARTMENT", "2 BEDROOM", "2 BATHROOM", "1400 SQ.FT"],
  },
  {
    id: "28",
    title: "Corner Unit Apartment",
    price: 1050000,
    type: "apartment",
    beds: 3,
    areasize: 1750,
    location: "Meydan",
    purpose: "buy",
    amenities: ["gym"],
    slug: "corner-unit-apartment-meydan",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (2).jpg",
    tags: ["APARTMENT", "3 BEDROOM", "3 BATHROOM", "1750 SQ.FT"],
  },
  {
    id: "29",
    title: "High Floor Marina Apartment",
    price: 1490000,
    type: "apartment",
    beds: 2,
    areasize: 1450,
    location: "Dubai Marina",
    purpose: "buy",
    amenities: ["gym", "pool"],
    slug: "high-floor-marina-apartment",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (3).jpg",
    tags: ["APARTMENT", "2 BEDROOM", "2 BATHROOM", "1450 SQ.FT"],
  },
  {
    id: "30",
    title: "City Walk Apartment",
    price: 1750000,
    type: "apartment",
    beds: 2,
    areasize: 1500,
    location: "City Walk",
    purpose: "buy",
    amenities: ["gym"],
    slug: "city-walk-apartment",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (1).jpg",
    tags: ["APARTMENT", "2 BEDROOM", "2 BATHROOM", "1500 SQ.FT"],
  },
  {
    id: "31",
    title: "Serene Garden Apartment",
    price: 830000,
    type: "apartment",
    beds: 1,
    areasize: 700,
    location: "Motor City",
    purpose: "buy",
    amenities: ["garden"],
    slug: "serene-garden-apartment-motor-city",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (2).jpg",
    tags: ["APARTMENT", "1 BEDROOM", "1 BATHROOM", "700 SQ.FT"],
  },
  {
    id: "32",
    title: "Luxury Duplex Penthouse",
    price: 9800000,
    type: "penthouse",
    beds: 5,
    areasize: 7400,
    location: "Downtown Dubai",
    purpose: "buy",
    amenities: ["gym", "pool"],
    slug: "luxury-duplex-penthouse-downtown",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (3).jpg",
    tags: ["PENTHOUSE", "5 BEDROOM", "6 BATHROOM", "7400 SQ.FT"],
  },
  {
    id: "33",
    title: "Affordable Apartment",
    price: 610000,
    type: "apartment",
    beds: 2,
    areasize: 900,
    location: "International City",
    purpose: "buy",
    amenities: [],
    slug: "affordable-apartment-international-city",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (1).jpg",
    tags: ["APARTMENT", "2 BEDROOM", "2 BATHROOM", "900 SQ.FT"],
  },
  {
    id: "34",
    title: "Premium Villa Community",
    price: 7200000,
    type: "villa",
    beds: 5,
    areasize: 6100,
    location: "Palm Jumeirah",
    purpose: "buy",
    amenities: ["pool", "garden"],
    slug: "premium-villa-community-palm",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (2).jpg",
    tags: ["VILLA", "5 BEDROOM", "6 BATHROOM", "6100 SQ.FT"],
  },
  {
    id: "35",
    title: "Skyline View Apartment",
    price: 1180000,
    type: "apartment",
    beds: 2,
    areasize: 1280,
    location: "Sheikh Zayed Road",
    purpose: "buy",
    amenities: ["gym", "pool"],
    slug: "skyline-view-apartment-szr",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (3).jpg",
    tags: ["APARTMENT", "2 BEDROOM", "2 BATHROOM", "1280 SQ.FT"],
  },
  {
    id: "36",
    title: "Community Park Villa",
    price: 3950000,
    type: "villa",
    beds: 4,
    areasize: 3900,
    location: "Tilal Al Ghaf",
    purpose: "buy",
    amenities: ["garden", "pool"],
    slug: "community-park-villa-tilal-al-ghaf",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (1).jpg",
    tags: ["VILLA", "4 BEDROOM", "4 BATHROOM", "3900 SQ.FT"],
  },
  {
    id: "2",
    title: "Luxury Apartment",
    price: 900000,
    type: "apartment",
    beds: 2,
    areasize: 1200,
    location: "Dubai Marina",
    purpose: "rent",
    amenities: ["gym"],
    slug: "luxury-apartment-marina",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (3).jpg",
    tags: ["VILLA", "1 BEDROOM", "2 BATHROOM", "839 SQ.FT"],
  },
  {
    id: "9",
    title: "JLT Furnished Apartment",
    price: 110000,
    type: "apartment",
    beds: 1,
    areasize: 780,
    location: "JLT",
    purpose: "rent",
    amenities: ["gym", "pool"],
    slug: "jlt-furnished-apartment",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (1).jpg",
    tags: ["APARTMENT", "1 BEDROOM", "1 BATHROOM", "780 SQ.FT"],
  },
  {
    id: "10",
    title: "Family Villa with Pool",
    price: 240000,
    type: "villa",
    beds: 4,
    areasize: 3500,
    location: "The Springs",
    purpose: "rent",
    amenities: ["pool", "garden"],
    slug: "family-villa-with-pool-springs",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (2).jpg",
    tags: ["VILLA", "4 BEDROOM", "4 BATHROOM", "3500 SQ.FT"],
  },
  {
    id: "11",
    title: "Modern Penthouse Rental",
    price: 520000,
    type: "penthouse",
    beds: 3,
    areasize: 2800,
    location: "Downtown Dubai",
    purpose: "rent",
    amenities: ["gym", "pool"],
    slug: "modern-penthouse-rental-downtown",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (3).jpg",
    tags: ["PENTHOUSE", "3 BEDROOM", "4 BATHROOM", "2800 SQ.FT"],
  },
  {
    id: "3",
    title: "Offplan Penthouse",
    price: 5000000,
    type: "penthouse",
    beds: 5,
    areasize: 5000,
    location: "Downtown Dubai",
    purpose: "offplan",
    amenities: ["pool", "gym"],
    slug: "offplan-penthouse",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (3).jpg",
    tags: ["VILLA", "1 BEDROOM", "2 BATHROOM", "839 SQ.FT"],
  },
  {
    id: "12",
    title: "Offplan Marina Residences",
    price: 1750000,
    type: "apartment",
    beds: 2,
    areasize: 1350,
    location: "Dubai Marina",
    purpose: "offplan",
    amenities: ["gym", "pool"],
    slug: "offplan-marina-residences",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (1).jpg",
    tags: ["APARTMENT", "2 BEDROOM", "2 BATHROOM", "1350 SQ.FT"],
  },
  {
    id: "13",
    title: "Offplan Villa Community",
    price: 4200000,
    type: "villa",
    beds: 4,
    areasize: 4300,
    location: "Dubai Hills Estate",
    purpose: "offplan",
    amenities: ["garden", "pool"],
    slug: "offplan-villa-community-dubai-hills",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (2).jpg",
    tags: ["VILLA", "4 BEDROOM", "4 BATHROOM", "4300 SQ.FT"],
  },
  {
    id: "14",
    title: "Offplan Skyline Penthouse",
    price: 7200000,
    type: "penthouse",
    beds: 4,
    areasize: 5400,
    location: "Business Bay",
    purpose: "offplan",
    amenities: ["gym", "pool"],
    slug: "offplan-skyline-penthouse-business-bay",
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
    image: "/assets/images/villa (3).jpg",
    tags: ["PENTHOUSE", "4 BEDROOM", "5 BATHROOM", "5400 SQ.FT"],
  },
];
