import { blogcard } from "@/types/blogcard";

export const blogs: blogcard[] = [
  {
    id: 1,
    title: "2025, Landmark Year: STAY DXB Achieves New Heights in Dubai’s Market",
    date: "DECEMBER 26, 2024",
    image: "/assets/images/blog-img-1.jpg",
    slug: "2025-landmark-year-stay-dxb-achieves-new-heights-dubai-market",
    category: "blog",
  },
  {
    id: 2,
    title: "2025, Landmark Year: STAY DXB Achieves New Heights in Dubai’s Market",
    date: "DECEMBER 26, 2024",
    image: "/assets/images/blog-img-2.jpg",
    slug: "2025-landmark-year-stay-dxb-achieves-new-heights-dubai-market-2",
    category: "blog",
  },
  {
    id: 3,
    title: "2025, Landmark Year: STAY DXB Achieves New Heights in Dubai’s Market",
    date: "DECEMBER 26, 2024",
    image: "/assets/images/blog-img-3.jpg",
    slug: "2025-landmark-year-stay-dxb-achieves-new-heights-dubai-market-3",
    category: "blog",
  },
  {
    id: 4,
    title: "2025, Landmark Year: STAY DXB Achieves New Heights in Dubai’s Market",
    date: "DECEMBER 26, 2024",
    image: "/assets/images/blog-img-4.jpg",
    slug: "2025-landmark-year-stay-dxb-achieves-new-heights-dubai-market-4",
    category: "blog",
  },
  {
    id: 5,
    title: "2025, Landmark Year: STAY DXB Achieves New Heights in Dubai’s Market",
    date: "DECEMBER 26, 2024",
    image: "/assets/images/blog-img-5.jpg",
    slug: "2025-landmark-year-stay-dxb-achieves-new-heights-dubai-market-5",
    category: "blog",
  },
  {
    id: 6,
    title: "2025, Landmark Year: STAY DXB Achieves New Heights in Dubai’s Market",
    date: "DECEMBER 26, 2024",
    image: "/assets/images/blog-img-6.jpg",
    slug: "2025-landmark-year-stay-dxb-achieves-new-heights-dubai-market-6",
    category: "blog",
  },
  {
    id: 7,
    title: "2025, Landmark Year: STAY DXB Achieves New Heights in Dubai’s Market",
    date: "DECEMBER 26, 2024",
    image: "/assets/images/blog-img-1.jpg",
    slug: "2025-landmark-year-stay-dxb-achieves-new-heights-dubai-market-7",
    category: "blog",
  },
  {
    id: 8,
    title: "2025, Landmark Year: STAY DXB Achieves New Heights in Dubai’s Market",
    date: "DECEMBER 26, 2024",
    image: "/assets/images/blog-img-2.jpg",
    slug: "2025-landmark-year-stay-dxb-achieves-new-heights-dubai-market-8",
    category: "blog",
  },
  {
    id: 9,
    title: "2025, Landmark Year: STAY DXB Achieves New Heights in Dubai’s Market",
    date: "DECEMBER 26, 2024",
    image: "/assets/images/blog-img-3.jpg",
    slug: "2025-landmark-year-stay-dxb-digital-marketing-insights",
    category: "marketing-insights",
  },
  {
    id: 10,
    title: "2025, Landmark Year: STAY DXB Achieves New Heights in Dubai’s Market",
    date: "DECEMBER 26, 2024",
    image: "/assets/images/blog-img-4.jpg",
    slug: "stay-dxb-marketing-growth-dubai-2025",
    category: "marketing-insights",
  },
  {
    id: 11,
    title: "2025, Landmark Year: STAY DXB Achieves New Heights in Dubai’s Market",
    date: "DECEMBER 26, 2024",
    image: "/assets/images/blog-img-5.jpg",
    slug: "real-estate-marketing-dubai-trends-2025",
    category: "marketing-insights",
  },
  {
    id: 12,
    title: "2025, Landmark Year: STAY DXB Achieves New Heights in Dubai’s Market",
    date: "DECEMBER 26, 2024",
    image: "/assets/images/blog-img-6.jpg",
    slug: "dubai-property-market-insights-2025-stay-dxb",
    category: "marketing-insights",
  },
];